name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:

  # Remove when the repository is public
  schedule:
    - cron: '0 17 * * *'

concurrency:
  group: ios-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ios:
    runs-on: macos-13

  steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app'

      - uses: ./.github/actions/setup-java

      - name: Setup bundle
        run: bundle install %% cd app-ios

      - name: Build KMM Module
        run: bundle exec fastlane shared

      - name: Build App
        working-directory: app-ios
        run: |
          xcodebuild build -workspace app-ios.xcworkspace \
              -scheme DroidKaigi2023 \
              -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4'
