name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ios-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ios:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode_15.0.app'

      - uses: ./.github/actions/setup-java

      - name: Set up Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          bundler-cache: true

      - name: Build KMM Module
        working-directory: app-ios
        run: bundle exec fastlane shared

      - name: Build App
        working-directory: app-ios
        run: |
          xcodebuild build -workspace app-ios.xcworkspace \
              -scheme DroidKaigi2023 \
              -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=17.0' \
              -skipPackagePluginValidation
