name: "cache SPM"
description: "select xcode defined at .xcode-version"
runs:
  using: "composite"
  steps:
    - name: cache SPM
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
      with:
        path: |
          app-ios/build/DerivedData/SourcePackages
        key: v1-konan-${{ runner.os }}-${{ hashFiles('.xcode-version') }}-${{ hasFiles('app-ios/Modules/Package.swift') }}-${{ hasFiles('app-ios/App/DroidKaigi2023/DroidKaigi2023.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: |
          v1-konan-${{ runner.os }}-${{ hashFiles('.xcode-version') }}-${{ hasFiles('app-ios/Modules/Package.swift') }}-${{ hasFiles('app-ios/App/DroidKaigi2023/DroidKaigi2023.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          v1-konan-${{ runner.os }}-${{ hashFiles('.xcode-version') }}-${{ hasFiles('app-ios/Modules/Package.swift') }}

    - uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b # v2
      id: spm-cache
      with:
        files: "app-ios/build/DerivedData/SourcePackages"

    - if: steps.spm-cache.outputs.files_exists != 'true'
      working-directory: app-ios
      shell: bash
      run: bundle exec fastlane resolved_package
